sym: sym.c sym2.c
	gcc -Wall -Wextra -Werror -std=c2x -Ofast -o sym sym.c -lcrypto
	gcc -Wall -Wextra -Werror -std=c2x -Ofast -o sym2 sym2.c -lcrypto

sizeof: sizeof.c
	gcc -Wall -Wextra -Werror -std=c2x -o sizeof sizeof.c


